// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzTSaAYxHinEpewaavd5EMeg3yecuih8',
    appId: '1:809102950410:web:f0b3e121b8227117f19ff3',
    messagingSenderId: '809102950410',
    projectId: 'test-flutter-e2ee',
    authDomain: 'test-flutter-e2ee.firebaseapp.com',
    storageBucket: 'test-flutter-e2ee.firebasestorage.app',
    measurementId: 'G-PFNE4R53L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgh7cjJQENqzUNeXLhwvpLTc8AgUEXEk',
    appId: '1:809102950410:android:045c48f1b7b32898f19ff3',
    messagingSenderId: '809102950410',
    projectId: 'test-flutter-e2ee',
    storageBucket: 'test-flutter-e2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr77DSVg37QjTP-dG1PtCI13Ik1TNrGhs',
    appId: '1:809102950410:ios:52ff3ed4fb9beed6f19ff3',
    messagingSenderId: '809102950410',
    projectId: 'test-flutter-e2ee',
    storageBucket: 'test-flutter-e2ee.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr77DSVg37QjTP-dG1PtCI13Ik1TNrGhs',
    appId: '1:809102950410:ios:52ff3ed4fb9beed6f19ff3',
    messagingSenderId: '809102950410',
    projectId: 'test-flutter-e2ee',
    storageBucket: 'test-flutter-e2ee.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIzTSaAYxHinEpewaavd5EMeg3yecuih8',
    appId: '1:809102950410:web:3482e1bf4b823b54f19ff3',
    messagingSenderId: '809102950410',
    projectId: 'test-flutter-e2ee',
    authDomain: 'test-flutter-e2ee.firebaseapp.com',
    storageBucket: 'test-flutter-e2ee.firebasestorage.app',
    measurementId: 'G-ZGSTWEL072',
  );
}
